Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-10, with the labels that each got.

#403 cambios en la migración affiliate_tokens
  database/migrations/2022_08_03_211508_create_affiliate_tokens_table.php
Labels: enhancement

#406 Implementación Seeders y refactorizado de modelos
  .env.example
  app/Models/Affiliate/Affiliate.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Models/Loan/Loan.php
  app/Models/Notification/NotificationCarrier.php
  app/Models/Notification/NotificationNumber.php
  database/seeders/DatabaseSeeder.php
  database/seeders/NotificationCarrierSeeder.php
Labels: enhancement, refactor

#415 Instalación de sanitizer request y refactorización del estado de cuenta del afiliado
  app/Http/Controllers/Affiliate/AffiliateController.php
  app/Http/Requests/Affiliate/AddressRequest.php
  app/Http/Requests/Affiliate/AffiliateRequest.php
  composer.json
  composer.lock
  config/app.php
Labels: refactor

#423 Refactorización método de estado de credenciales
  app/Http/Controllers/Affiliate/AffiliateController.php
  app/Http/Controllers/Contribution/ContributionController.php
Labels: refactor
