Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-05, with the labels that each got.

#293 adicion de respuesta con Excel
  app/Http/Controllers/Contribution/ImportPayrollCommandController.php
Labels: refactor

#309 adicion de guardao del estado del afiliado
  app/Http/Controllers/Contribution/ImportPayrollCommandController.php
  database/migrations/2022_05_10_205841_create_function_registration_payroll_command.php
Labels: Data base

#314 actualizacion de datos del afiliado
  app/Http/Controllers/Contribution/ImportPayrollCommandController.php
  database/migrations/2021_12_15_154508_create_contribution_copy_payroll_commands_table.php
  database/migrations/2022_05_16_204209_create_update_affiliate_command.php
  database/seeders/ContributionRolePermissionSeeder.php
Labels: enhancement, Data base

#316 adicion de restricción de actualizacion de afiliado de comando
  database/migrations/2022_05_16_204209_create_update_affiliate_command.php
Labels: refactor

#319 restriccion creacion de esposas sin identity_card
  database/migrations/2022_02_09_154306_create_function_update_or_create_spouse_and_update_affiliate.php
Labels: bug

#328 Función para validar la contribución is_valid true tabla contribution_passives
  database/migrations/2022_05_27_143444_create_function_import_contribution_eco_com.php
  database/migrations/2022_05_27_170733_create_function_tmp_contribution_eco_com.php
Labels: enhancement

#330 cambio de validacion
  database/migrations/2022_05_27_143444_create_function_import_contribution_eco_com.php
  database/migrations/2022_05_27_170733_create_function_tmp_contribution_eco_com.php
Labels: refactor
