Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-03, with the labels that each got.

#165 creación de métodos para crea conexión en base de datos
  .env.example
  app/Helpers/Util.php
  app/Http/Controllers/Temporary/TmpCopyDataSenasirController.php
  database/migrations/2022_03_03_173952_create_extension_dblink.php
Labels: enhancement

#167 metodos para importacion de ids persona senasir tipo viudedad
  app/Http/Controllers/Temporary/TmpCopyDataSenasirController.php
  database/migrations/2022_03_07_125446_create_function_verification_for_import_senasir.php
  database/migrations/2022_03_07_130114_create_function_import_affiliates_senasir.php
  routes/api_temporary.php
Labels: Data base

#174 refactorizacion listado de meses validados de planilla senasir
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
  routes/api_contribution.php
Labels: documentation, enhancement

#175 cambio por variable
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: bug

#183 validación en la importación de contribuciones
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
  database/migrations/2022_01_25_180946_create_function_contribution_affiliate_senasir_create_or_update.php
  database/migrations/2022_02_01_173734_create_tmp_registration_aid_contributions_table.php
  database/migrations/2022_02_09_154306_create_function_update_or_create_spouse_and_update_affiliate.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_ids_senasir.php
Labels: bug, documentation

#184 se agrega tracsccion al metodo import_create_or_update_contribution_p…
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
Labels: bug

#192 Creacion Modelo PayrollValidatedSenasir
  app/Models/Contribution/PayrollValidatedSenasir.php
Labels: Data base

#203 Creacion del Modelo AffiliateState
  app/Models/Affiliate/AffiliateState.php
  app/Models/Affiliate/AffiliateStateType.php
  app/Models/Affiliate/Category.php
  app/Models/Affiliate/Degree.php
  app/Models/Affiliate/Hierarchy.php
Labels: Data base

#209 modificacion de variables
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_02_21_161533_create_copy_person_senasirs_table.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: refactor

#211 modificacion de metodo de actualizacion de afiliados
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: refactor

#216 Función para actualizar id_peson_senasir apartir del id_afiliados
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: enhancement

#218 Refactorizacion de metodos de impotacion contribuciones senasir
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
  database/migrations/2022_01_25_180946_create_function_contribution_affiliate_senasir_create_or_update.php
  database/migrations/2022_02_09_154306_create_function_update_or_create_spouse_and_update_affiliate.php
Labels: refactor

#220 cambio de nombre de la migracion payroll_validate_senasir por payroll_senasir
  database/migrations/2021_12_28_180407_create_payroll_senasirs_table.php
Labels: refactor

#222 arreglo de bug de variables
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: bug

#225 Creación de la tabla contribution_passive
  database/migrations/2021_12_29_212927_add_columns_to_aid_contributions.php
  database/migrations/2021_12_29_212927_create_contribution_passives_table.php
  database/migrations/2022_02_01_173734_create_tmp_registration_aid_contributions_table.php
  routes/api_temporary.php
  storage/api-docs/api-docs.json
Labels: enhancement

#226 cambio de tipo de dato de contributionpassive
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
  database/migrations/2022_01_21_151719_create_function_serch_affiliate_period_senasir.php
  database/migrations/2022_01_25_180946_create_function_contribution_affiliate_senasir_create_or_update.php
  database/migrations/2022_01_26_172457_create_function_import_period_contribution_senasir.php
Labels: refactor

#228 agregar validacion al metodo tmp_update_affiliate_id_person_senasir
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: bug

#232 creación y actualización de esposas a la funcion tmp_create_function_update_affiliate_id_person_senasir
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: refactor

#236 Reportes importación SENASIR de contribución y planilla
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
  routes/api_contribution.php
Labels: enhancement

#237 adicion de metodo para conteo de tramite, columnas de la tabla copy p…
  database/migrations/2022_02_21_161533_create_copy_person_senasirs_table.php
  database/migrations/2022_03_05_125446_create_function_verification_for_import_senasir.php
Labels: Data base
