Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-12, with the labels that each got.

#464 Implementación del reporte
  app/Exports/NotificacitonSendExport.php
  app/Helpers/Util.php
  app/Http/Controllers/Notification/NotificationController.php
  routes/api_notification.php
Labels: enhancement, refactor

#466 corrección bug para envío masivo
  app/Http/Controllers/Notification/NotificationController.php
Labels: bug, refactor

#469 arreglando reporte de notificaciones
  app/Exports/NotificacitonSendExport.php
  app/Http/Controllers/Notification/NotificationController.php
Labels: bug, refactor

#482 modificacion metodo de filtrado
  app/Http/Controllers/Contribution/ContributionController.php
Labels: enhancement

#484 adicion ruta contactos
  app/Http/Controllers/CityController.php
  routes/api_app.php
Labels: enhancement

#492 adicion de filtro de busqueda de id de estado sec pasivo
  app/Http/Controllers/Contribution/ContributionPassiveController.php
Labels: enhancement
