Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-02, with the labels that each got.

#125 modificacion metodo para reacer paso 1 y 2
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: enhancement

#127 creación de tabla para el registro contribuciones antes de ser actualizada
  database/migrations/2022_01_25_180946_create_function_contribution_affiliate_senasir_create_or_update.php
  database/migrations/2022_02_01_173734_create_temporary_registration_aid_contributions_table.php
Labels: enhancement

#128 ajuste metodo para la visualizacion del progreso de la importacion
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: enhancement

#129 modificacion de metodos 1 y 2 en respuestas
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: enhancement

#130 usuarios
  app/Http/Controllers/Admin/UserController.php
  app/Http/Requests/Admin/UserRequest.php
Labels: enhancement

#131 configuracion para acceso de rutas
  app/Http/Middleware/VerifyCsrfToken.php
Labels: enhancement

#132 ci users y busqueda ldap
  app/Http/Controllers/Admin/UserController.php
  database/migrations/2022_02_04_134205_add_column_user_identity_card.php
  routes/api_admin.php
Labels: enhancement

#133 user identity_card
  app/Http/Controllers/Admin/UserController.php
Labels: enhancement

#138 modificacion del metodo del paso 2 adicion de informacion en el arch…
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
  database/migrations/2022_01_21_211935_create_function_registration_aid_contribution_affiliate_payroll_senasir.php
Labels: enhancement

#140 adicion de validadcion en paso 1, 2 y correccion de mensaje de error paso 1
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: enhancement

#143 Crear Función par crear o actualizar datos de la esposa y actualizar algunos datos del afiliado en la importación senasir
  database/migrations/2022_01_26_172457_create_function_import_period_payroll_contribution_senasir.php
  database/migrations/2022_02_09_154306_create_function_update_or_create_spouse_and_update_affiliate.php
Labels: enhancement

#144 only active users
  app/Http/Controllers/Auth/AuthController.php
Labels: enhancement

#145 modificacion de respuestas
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: enhancement

#146 listado de meses senasir adicion de informacion de cantidades
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: refactor

#150 adicion de filtro en el copiado del archivo del primer paso considerando solo el perido selecionado
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
Labels: refactor

#152 Corrección del Seeder ContributionOriginSeeder
  app/Models/Affiliate/PensionEntity.php
  app/Models/Contribution/ContributionOrigin.php
  database/seeders/ContributionOriginSeeder.php
Labels: bug

#153 migraciones para la actualizacion de id persona senasir
  database/migrations/2022_02_21_160738_add_column_affiliate_id_person_senasir.php
  database/migrations/2022_02_21_161533_create_tmp_copy_data_senasirs_table.php
Labels: Data base

#154 Creacion de modelos action,aidContribution, creacion seeder permisos,…
  app/Models/Admin/Action.php
  app/Models/Contribution/AidContribution.php
  database/migrations/2022_02_21_161533_create_tmp_copy_data_senasirs_table.php
  database/seeders/ContributionPermissionSeedeer.php
Labels: enhancement, Data base

#160 documentación para el copiado de datos de afiliados y esposas a la tabla tmp_copy_data_senasirs
  app/Http/Controllers/Temporary/TmpCopyDataSenasirController.php
Labels: documentation, enhancement, refactor

#163 conexion de una nueva base de datos desde laravel
  .env.example
  config/database.php
  database/migrations/2022_02_21_161533_create_tmp_copy_data_senasirs_table.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement
