Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-09, with the labels that each got.

#377 Refactorización y modelos
  app/Http/Controllers/Contribution/AppContributionController.php
  app/Models/Affiliate/Affiliate.php
  app/Models/Loan/Loan.php
  app/Models/Observation.php
  routes/api_app.php
Labels: refactor

#378 Notificaciones implementadas
  app/Helpers/Util.php
  app/Http/Controllers/Notification/NotificationController.php
  app/Http/Requests/Notification/NotificationRequest.php
  app/Models/EconomicComplement/EcoComBeneficiary.php
  app/Models/EconomicComplement/EcoComModality.php
  app/Models/EconomicComplement/EcoComProcedure.php
  app/Models/EconomicComplement/EcoComState.php
  app/Models/EconomicComplement/EcoComStateType.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Models/Notification/NotificationCarrier.php
  app/Models/Notification/NotificationNumber.php
  app/Models/Notification/NotificationSend.php
  app/Models/ObservationType.php
  app/Providers/RouteServiceProvider.php
  routes/api_notification.php
  routes/console.php
Labels: enhancement

#379 Refactorización contribuciones
  app/Http/Controllers/Contribution/AppContributionController.php
  app/Models/Loan/Loan.php
  app/Models/Observation.php
  routes/api_app.php
Labels: refactor

#383 sincronizacion pva
  app/Http/Controllers/Admin/UserController.php
Labels: bug

#385 Listado prestamos por afiliado para la app
  app/Http/Controllers/Loan/LoanController.php
  app/Models/Loan/Loan.php
  app/Models/Loan/LoanDestiny.php
  app/Models/Loan/LoanInterest.php
  routes/api_app.php
Labels: enhancement

#388 Refactorización Backend Notificaciones
  app/Http/Controllers/Notification/NotificationController.php
  app/Models/Admin/Module.php
  routes/api_notification.php
Labels: refactor

#393 Contribuciones Pasivo Eco-Com pdf
  app/Http/Controllers/Contribution/AppContributionController.php
  resources/views/certification__contribution_eco_com.blade.php
  resources/views/print_global/police_info.blade.php
Labels: refactor

#396 Refactorización de modelos y Certificaciones de contribuciones #381
  app/Http/Controllers/Contribution/AppContributionController.php
  app/Models/Contribution/ContributionType.php
  app/Models/Contribution/Reimbursement.php
  app/Models/Loan/Loan.php
  app/Models/Loan/LoanDestiny.php
  app/Models/Loan/LoanGuaranteeRegister.php
  app/Models/Loan/LoanInterest.php
  app/Models/Loan/LoanPayment.php
  app/Models/Loan/LoanPlanPayment.php
  app/Models/Loan/LoanState.php
  app/Models/Loan/PaymentType.php
  app/Models/Loan/Sismu.php
  app/Providers/AppServiceProvider.php
  public/css/report-print.min.css
  resources/views/contribution/print/certification_contribution_active.blade.php
  resources/views/contribution/print/certification_contribution_eco_com.blade.php
Labels: refactor

#397 Formato moneda certificaciones de contribuciones #381
  app/Http/Controllers/Contribution/AppContributionController.php
  resources/views/contribution/print/certification_contribution_active.blade.php
  resources/views/contribution/print/certification_contribution_eco_com.blade.php
Labels: refactor
