Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-04, with the labels that each got.

#240 Se refactoriza funcion_update_affiliate_id_person_senasir para validar y actualizar datos de afiliados sin tramite
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: refactor

#244 método para actualizar ids de afiliado y contero de registros por criterio
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
  routes/api_temporary.php
Labels: enhancement

#247 Actualizacion de Id por criterio de carnet y matricula datos con revi…
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
  routes/api_temporary.php
Labels: enhancement

#249 funcion para actualizacion de datos del afiliado
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
  routes/api_temporary.php
Labels: enhancement

#250 creacion de afiliados y esposas
  app/Http/Controllers/Temporary/CopyPersonSenasirController.php
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
  routes/api_temporary.php
Labels: enhancement, Data base

#251 ajuste en la actualizacion de datos del afiliado
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: enhancement

#254 actualización de fecha de nacimiento de afiliado de la importación de ids
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: enhancement

#261 Renombramiento de variables payroll senasirs y contribution_passives
  app/Http/Controllers/Contribution/ImportContributionSenasirController.php
  app/Http/Controllers/Contribution/ImportPayrollSenasirController.php
  app/Models/Contribution/ContributionPassive.php
  app/Models/Contribution/PayrollSenasir.php
  database/migrations/2021_12_28_180407_create_payroll_senasirs_table.php
  database/migrations/2021_12_29_212927_create_contribution_passives_table.php
  database/migrations/2022_01_25_180946_create_function_contribution_affiliate_senasir_create_or_update.php
  database/migrations/2022_01_26_172457_create_function_import_period_contribution_senasir.php
  database/migrations/2022_02_09_154306_create_function_update_or_create_spouse_and_update_affiliate.php
Labels: refactor

#262 ajustes a la actualizacion del estado del afiliado
  database/migrations/2022_03_06_220540_tmp_create_function_update_affiliate_id_person_senasir.php
Labels: refactor

#263 ajuste a la actualizacion de datos del afiliado
  database/migrations/2022_02_09_154306_create_function_update_or_create_spouse_and_update_affiliate.php
Labels: refactor
