Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-11, with the labels that each got.

#434 Primera versión SMS's
  app/Helpers/Util.php
  app/Http/Controllers/Notification/SMSController.php
  config/database.php
  routes/api_notification.php
Labels: enhancement

#441 Filtrado y listado de contribuciones
  app/Http/Controllers/Contribution/ContributionController.php
  app/Http/Controllers/Contribution/ContributionPassiveController.php
  routes/api_contribution.php
Labels: documentation, refactor

#450 Refactorización de certificaciones de contribuciones
  app/Http/Controllers/Contribution/AppContributionController.php
  app/Http/Controllers/Contribution/ContributionController.php
  app/Http/Controllers/Contribution/ContributionPassiveController.php
  resources/views/contribution/print/app_certification_contribution_eco_com.blade.php
  resources/views/contribution/print/certification_contribution_eco_com.blade.php
  resources/views/spouse/spouse_info.blade.php
Labels: refactor

#453 agregando .env.example
  .env.example
Labels: refactor

#457 agregando firebase token is not null en tablas temporales
  app/Http/Controllers/Notification/NotificationController.php
Labels: refactor
