Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2022-08, with the labels that each got.

#361 Refactorización ProcedureQR - QuotaAidMortuary
  app/Http/Controllers/ProcedureQRController.php
  app/Models/Affiliate/BaseWage.php
  app/Models/QuotaAidMortuary/QuotaAidBeneficiary.php
Labels: refactor

#363 Implementación de una base de datos
  app/Models/Notification/NotificationCarrier.php
  app/Models/Notification/NotificationNumber.php
  app/Models/Notification/NotificationSend.php
  database/migrations/2022_08_03_193033_create_notification_numbers_table.php
  database/migrations/2022_08_03_193055_create_notification_carriers_table.php
  database/migrations/2022_08_03_193115_create_notification_sends_table.php
Labels: enhancement, Data base

#367 Cambio de directorio de TokenAffiliate
  app/Models/Affiliate/AffiliateToken.php
Labels: enhancement

#369 Refactorización y migración
  app/Http/Controllers/ProcedureQRController.php
  app/Models/Affiliate/AffiliateUser.php
  database/migrations/2022_08_05_200249_create_affiliate_users_table.php
Labels: refactor

#373 AffiliateController y Modelos polimórficos
  app/Helpers/Util.php
  app/Http/Controllers/Affiliate/AffiliateController.php
  app/Models/Admin/Role.php
  app/Models/Affiliate/Address.php
  app/Models/Affiliate/Affiliate.php
  app/Models/Affiliate/Spouse.php
  app/Models/Contribution/Contribution.php
  app/Models/Loan/Loan.php
  app/Models/Loan/LoanContributionAdjust.php
  app/Models/Loan/Record.php
  app/Models/Loan/RecordType.php
  app/Models/QuotaAidMortuary/QuotaAidBeneficiary.php
  app/Models/QuotaAidMortuary/QuotaAidMortuary.php
  app/Models/RetirementFund/RetFunBeneficiary.php
  app/Models/RetirementFund/RetFunObservation.php
  app/Models/RetirementFund/RetirementFund.php
  app/Models/Voucher.php
  app/Providers/AppServiceProvider.php
  routes/api_affiliate.php
Labels: refactor

#374 Creacion de credenciales y autentificacion de usuarios oficina virtual
  app/Http/Controllers/Affiliate/AffiliateUserController.php
  routes/api_global.php
Labels: enhancement
