Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2023-01, with the labels that each got.

#510 Refactorización de código de notificaciones
  app/Exports/NotificationSendExport.php
  app/Helpers/Util.php
  app/Http/Controllers/Notification/NotificationController.php
  app/Http/Controllers/Notification/SMSController.php
  app/Jobs/ProcessNotification.php
  app/Jobs/ProcessRegisterNotification.php
  app/Models/Affiliate/Affiliate.php
  app/Models/Notification/NotificationSend.php
  config/queue.php
  database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  database/migrations/2022_12_20_112341_create_jobs_table.php
  database/migrations/2023_01_10_102156_add_column_destination_number_to_notification_sends.php
  routes/api_notification.php
Labels: bug, refactor

#511 Implementación de tabla notification_types
  app/Http/Controllers/Notification/NotificationController.php
  app/Models/Notification/NotificationSend.php
  app/Models/Notification/NotificationType.php
  database/migrations/2023_01_10_102156_add_column_destination_number_to_notification_sends.php
  database/migrations/2023_01_10_155352_create_notification_types_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/NotificationTypeSeeder.php
Labels: enhancement

#512 Refactorización de nombre de columna en la tabla notification_sends
  app/Http/Controllers/Notification/NotificationController.php
  app/Jobs/ProcessRegisterNotification.php
  app/Models/Notification/NotificationNumber.php
  database/migrations/2023_01_17_113717_remove_column_number_id_from_notification_sends.php
  database/migrations/2023_01_17_122753_remove_column_destination_number_from_notification_sends.php
Labels: refactor

#513 ordenado por meses del listado de aportes
  app/Http/Controllers/Contribution/AppContributionController.php
Labels: bug

#514 descomentando codigo del envio de notificaciones
  app/Helpers/Util.php
  app/Http/Controllers/Notification/SMSController.php
  database/seeders/NotificationCarrierSeeder.php
  database/seeders/NotificationNumberSeeder.php
  database/seeders/NotificationTypeSeeder.php
Labels: refactor

#517 Marca de agua en PDF para kardex
  resources/views/loan/payment_kardex.blade.php
Labels: refactor
