Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BACKEND, pull requests merged in 2024-05, with the labels that each got.

#682 Actualizacion de Laravel 9 a 10
  app/Http/Kernel.php
  composer.json
  composer.lock
Labels: update

#685 Corrigiendo bug de generación de reporte SMS y Notificaciones
  app/Http/Controllers/Notification/NotificationController.php
  app/Jobs/ProcessRegisterNotification.php
Labels: bug, refactor

#684 Actualizacion de la función de BD import_contribution_eco_com
  database/migrations/2024_05_14_114515_update_function_import_contribution_eco_com.php
Labels: Data base, update

#689 Modelos de Pagos en Demasía
  app/Models/Devolution.php
  app/Models/Due.php
  app/Models/EconomicComplement/EcoComMovement.php
Labels: enhancement

#691 Creación de controlador de EcoComProcedure y función para listar
  app/Http/Controllers/EconomicComplement/EcoComProcedureController.php
Labels: enhancement

#693 APIS pagos en demasía
  app/Providers/RouteServiceProvider.php
  routes/api_economic_complement.php
Labels: enhancement

#694 Creación del controlador EcoComMovement
  app/Http/Controllers/EconomicComplement/EcoComMovementController.php
Labels: enhancement

#696 API's para registrar deudas y listar el los movimientos de pagos en demasía
  app/Http/Controllers/EconomicComplement/EcoComMovementController.php
  routes/api_economic_complement.php
Labels: enhancement

#697 Creación de modelos de pagos directos
  app/Models/EconomicComplement/EcoComDirectPayment.php
Labels: enhancement

#699 API para registrar Pagos directos
  app/Http/Controllers/EconomicComplement/EcoComMovementController.php
  app/Models/Devolution.php
  app/Models/EconomicComplement/DiscountTypeEconomicComplement.php
  app/Models/EconomicComplement/EcoComDirectPayment.php
  app/Models/EconomicComplement/EcoComMovement.php
  routes/api_economic_complement.php
Labels: enhancement

#701 API para eliminar el ultimo registro de movimiento de dinero
  app/Http/Controllers/EconomicComplement/EcoComMovementController.php
  app/Models/Due.php
  routes/api_economic_complement.php
Labels: enhancement

#706 Reporte de Movimientos de pagos en demasía
  app/Exports/EcoComMovementsExport.php
  app/Http/Controllers/ReportController.php
  routes/api_economic_complement.php
Labels: enhancement

#707 rutas autenticadas
  app/Observers/EcoComMovementObserver.php
  app/Providers/EcoComMovementObserverServiceProvider.php
  config/app.php
  routes/api_economic_complement.php
Labels: refactor
